<?php

define( 'ALLOGGIO_MEMBERSHIP_VERSION', '1.0.2' );
define( 'ALLOGGIO_MEMBERSHIP_ABS_PATH', dirname( __FILE__ ) );
define( 'ALLOGGIO_MEMBERSHIP_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'ALLOGGIO_MEMBERSHIP_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'ALLOGGIO_MEMBERSHIP_ASSETS_PATH', ALLOGGIO_MEMBERSHIP_ABS_PATH . '/assets' );
define( 'ALLOGGIO_MEMBERSHIP_ASSETS_URL_PATH', ALLOGGIO_MEMBERSHIP_URL_PATH . 'assets' );
define( 'ALLOGGIO_MEMBERSHIP_INC_PATH', ALLOGGIO_MEMBERSHIP_ABS_PATH . '/inc' );
define( 'ALLOGGIO_MEMBERSHIP_INC_URL_PATH', ALLOGGIO_MEMBERSHIP_URL_PATH . 'inc' );
define( 'ALLOGGIO_MEMBERSHIP_LOGIN_MODAL_PATH', ALLOGGIO_MEMBERSHIP_INC_PATH . '/login-modal' );
define( 'ALLOGGIO_MEMBERSHIP_LOGIN_MODAL_URL_PATH', ALLOGGIO_MEMBERSHIP_INC_URL_PATH . 'login-modal' );
